### PR TITLE
Handling clear/set/get of JPEG header comment via libexiv2

### PR DESCRIPTION
**Pull request by dgtlmoon**
As well supported by the `libexiv2-dev` interface, support for the JPEG Header comment field, technically this is also metadata :+1: 

I'm testing/building like this on Ubuntu/Debian, python3.6

```
cd pyexiv2/lib/
g++ exiv2api.cpp -o py36-linux/exiv2api.so -O3 -Wall -std=c++11 -shared -fPIC `python3 -m pybind11 --includes` -I /usr/include/exiv2 -I /usr/include/python3 -L ./lib -l exiv2
cd ../..
python3 setup.py install
pytest -v
```

### CODE REVIEW

**Comment by LeoHsiao1** [comment]
Thank you for all your work.
I found the [code](https://github.com/Exiv2/exiv2/blob/68d65d0f0c41b0c4f9411354d5fa0d15641ac087/samples/metacopy.cpp#L75) for Comment in EXIV2, but I wasn't sure it belonged to JPEG Comment.
Are you in a hurry to implement this feature? I'd like to wait until the New Year holidays to add this feature.

**Comment by LeoHsiao1** [comment]
In addition, please submit this PR to the `dev` branch.
I will merge it into the `master` branch after all the platforms and all the Python versions have been tested.

**Comment by dgtlmoon** [comment]
Maybe a better idea is to have the comment available as an attribute of Image, instead of `get_comment()` ?

**Comment by dgtlmoon** [comment]
Nearly everyone does not realise that JPEG Header comment != EXIF Comment.... It is also the responsilbity of any documentation to make sure the user knows this.

Slightly better documentation can save people months of heart-ache when they realise some information is there that should not be, or they think it's a bug

So in this case, it can lead to leaking information, personal data, identifying information, etc.. super important to have this I think, maybe another idea can be to have a 

`self.img.clear_all_metadata()`  that clears
- EXIF
- XMP
- IPTC
- JPEG Header Comment
- Any other data (there is also record of date/time modified/created etc)
-

an idea..

**Comment by LeoHsiao1** [comment]
Oh, I also wrote an API called `img.clear_all()` before.
But I later realized that the meaning of `all` was ambiguous, and that there were dozens of standards for metadata, of which I could only delete EXIF, IPTC and XMP. So I removed the API.

**Comment by LeoHsiao1** [comment]
As you can see from the ExifTool [documentation](https://exiftool.org/TagNames/index.html), there are too many types of image metadata. Exiv2 mainly supports three kinds of metadata: EXIF, IPTC and XMP.
Users often only care about what kind of image metadata they see on their phones and computers.
For example, when I looked at your previous photo using the professional software `adobe Bridge`, the metadata displayed was empty, so I thought there was no data on the image.

**Comment by dgtlmoon** [comment]
> Oh, I also wrote an API called `img.clear_all()` before.
> But I later realized that the meaning of `all` was ambiguous, and that there were dozens of standards for metadata, of which I could only delete EXIF, IPTC and XMP. So I removed the API.

Yeah ok, agreed, well, in 99% of cases just using the existing libexiv2 functionality for handling comments would be really wonderful, looking forwards to seeing this pull request merged..

**Comment by dgtlmoon** [comment]
@LeoHsiao1 Please remove `Can't read/write image structure which is not metadata, such as JPEG Comment ` from the `README.md` ...

**Comment by LeoHsiao1** [comment]
Oh, I'll update the document after I merge this PR into the master branch.

**Comment by LeoHsiao1** [comment]
I've written the API for JPEG Comment and I'm writing the test case now.
I will also check the ability to read and write ICC profile in the image, so I cannot release a new version today.

**Comment by dgtlmoon** [comment]
@LeoHsiao1 You've completely confused me again - there is already `def test_modify_jpeg_header_comments():` ... ?

**Comment by dgtlmoon** [comment]
Are you using the actual code from peoples pull requests or are you just rewriting it entirely??

**Comment by LeoHsiao1** [comment]
Although you have done most of the work, there is still something to be done.
For example:
- You did not use encoding parameters in `set_comment()`, resulting in unsupported Unicode characters.
- Not executed `(*img)->writeMetadata();` in `set_comment()`, resulting changes will not be saved to the image.
- I need to add test cases to check the impact of COMMENT on PNG and other format images.

**Comment by dgtlmoon** [comment]
@LeoHsiao1 `I've written the API for JPEG Comment and I'm writing the test case now.` ... I'm completely confused! I've already written this as part of this pull request !?!?!?

**Comment by dgtlmoon** [comment]
OK! Got it, sorry man, If you add a little more information in your comments it helps a lot! thanks again

**Comment by LeoHsiao1** [comment]
Thank you for your work. It was only during the test that I found your code needed to be modified.
I just found out that I can add `Comment` to a PNG image, but I can't see it with exifTool.

**Pull request merged**
